##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/caja-extensions
    - autoconf-archive
    - caja
    - clang
    - dbus-glib
    - gcc
    - git
    - gupnp
    - imagemagick
    - make
    - mate-common
    - python
    - samba
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/caja-extensions
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - libcaja-extension-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libgtk-3-dev
    - libgupnp-1.2-dev
    - libmate-desktop-dev
    - libstartup-notification0-dev
    - libxml2-utils
    - make
    - mate-common
    - pkg-config

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/caja-extensions.git
    - autoconf-archive
    - caja-devel
    - clang
    - clang-analyzer
    - dbus-glib-devel
    - dbus-glib-devel
    - gajim
    - gcc
    - git
    - gtk3-devel
    - gupnp-devel
    - make
    - mate-common
    - mate-desktop-devel
    - redhat-rpm-config

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - gcc
    - git
    - libcaja-extension-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libgtk-3-dev
    - libgupnp-1.2-dev
    - libmate-desktop-dev
    - libstartup-notification0-dev
    - libxml2-utils
    - make
    - mate-common
    - pkg-config

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - cd ${START_DIR}
  - '[ -f mate-common-1.24.1.tar.xz ] || curl -Ls -o mate-common-1.24.1.tar.xz https://github.com/mate-desktop/mate-common/releases/download/v1.24.1/mate-common-1.24.1.tar.xz'
  - tar xf mate-common-1.24.1.tar.xz
  - cd mate-common-1.24.1
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude -i'caja-1.22.0' .
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: caja-extensions-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
